# Generated by Django 5.0.6 on 2024-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='week',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='time',
            name='week',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='turfbooked',
            name='slots',
            field=models.TextField(default=''),
        ),
    ]
